# Generated by Django 5.2.17 on 2026-10-10 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('contribution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('frequency', models.CharField(choices=[('QUOTIDIENNE', 'Quotidienne'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUELLE', 'Mensuelle'), ('PERSONNALISEE', 'Personnalisée')], default='MENSUELLE', max_length=20)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminée'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tontines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
