# Generated by Django 5.2.17 on 2026-10-10 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBRE', 'Membre'), ('COLLECTEUR', 'Collecteur')], default='MEMBRE', max_length=12)),
                ('status', models.CharField(choices=[('INVITE', 'Invité'), ('ACTIF', 'Actif'), ('PARTI', 'Parti')], default='ACTIF', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='tontines.tontine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations_tontines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tontine', 'user'), name='unique_user_per_tontine')],
            },
        ),
    ]
