# Generated by Django 5.2.17 on 2026-10-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Membre'), ('COLLECTOR', 'Collecteur'), ('AUDITOR', 'Admin / Auditeur')], default='MEMBER', max_length=20),
        ),
    ]
