# Generated by Django 5.2.17 on 2026-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Membre'), ('COLLECTOR', 'Collecteur'), ('ADMIN', 'Administrateur'), ('AUDITOR', 'Auditeur')], default='MEMBER', max_length=20),
        ),
    ]
